[images]
  remote_images = ["https://upload.wikimedia.org/", "https://static.wikia.nocookie.net/", "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/", "https://static1.srcdn.com/"]

[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
